buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.4.2'
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.medicaldisplay'
    compileSdk 34
    ndkVersion '25.2.9519653'

    defaultConfig {
        minSdk 33
        targetSdk 34

        externalNativeBuild {
            ndkBuild {
                arguments 'NDK_APPLICATION_MK=jni/Application.mk', 'APP_STL=c++_shared'
                cppFlags '-std=c++17', '-fexceptions', '-frtti'
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
        }
    }

    buildFeatures {
        aidl = true
        buildConfig = true
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['java']
            aidl.srcDirs = ['aidl']
            res.srcDirs = ['res']
            jniLibs.srcDirs = ['libs']
            assets.srcDirs = ['assets']
        }
    }

    externalNativeBuild {
        ndkBuild {
            path file('jni/Android.mk')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.8.0'
}
